In [2]:
import numpy as np 
arr=np.array([[1,2,3],[9,10,20]])
print(arr.flatten())

[ 1  2  3  9 10 20]


In [4]:
print(arr.flatten("F"))
print(arr.flatten("C"))
print(arr.flatten("A"))
print(arr.flatten("K"))

[ 1  9  2 10  3 20]
[ 1  2  3  9 10 20]
[ 1  2  3  9 10 20]
[ 1  2  3  9 10 20]


In [11]:
import numpy as np
arr2 = np.array([[1,2,3]
        ,[4,5,6],
        [7,8,9]])
print(arr2.transpose())
arr3=np.array([[1,2],[3,4],[5,6]])
print(arr3.transpose(1,0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 3 5]
 [2 4 6]]


In [16]:
import numpy as np
arr = [20, 2, 7, 1, 34]
print("arr : ", arr) 
print("mean of arr : ", np.mean(arr))
print(np.mean(arr, axis = 0))  

arr :  [20, 2, 7, 1, 34]
mean of arr :  12.8
12.8


In [17]:
import numpy as np 
arr = [20, 2, .2, 10, 4] 
print("\nSum of arr : ", np.sum(arr)) 


Sum of arr :  36.2


In [19]:
# numpy.dot() method
import numpy as np

# Scalars
product = np.dot(5, 4)
print("Dot Product of scalar values  : ", product)
vector_a = 8 + 3j
vector_b = 4 + 3j

product = np.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product of scalar values  :  20
Dot Product  :  (23+36j)


In [21]:
import numpy as np
vector_a = np.array([[8, 4], [5, 4]])
vector_b = np.array([[2, 5], [1, 2]])

product = np.dot(vector_a, vector_b)
print("Dot Product  : \n", product)

product = np.dot(vector_b, vector_a)
print("\nDot Product  : \n", product)

Dot Product  : 
 [[20 48]
 [14 33]]

Dot Product  : 
 [[41 28]
 [18 12]]


In [22]:
import numpy as np
a = 0.3 + 0.6
b = 0.9
print(a == b)          
print(np.isclose(a, b))    
print(np.allclose([1.0, 2.0], [1.0000001, 2.0]))  # True


False
True
True


In [23]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A * B) 
print(np.matmul(A, B)) 


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
