In [12]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
import numpy as np

random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 4)
randint_array = np.random.randint(1, 10, size=(2, 3))

print(random_array)
print(normal_array)
print(randint_array)

[[0.13262068 0.5819246  0.02992465]
 [0.28700726 0.62773317 0.26301656]]
[[ 0.95117733 -2.474124    0.1548036   0.39601704]
 [-0.26690711 -0.7475396   1.48442843  0.26029056]]
[[7 1 5]
 [6 5 7]]


In [20]:
arr1=np.array([[1,2,3,4,5],[7,8,3,6,8]])
print(arr1[1,2])

3


In [21]:
import numpy as np
arr2 = np.array([9, 1, 3, 3, 2, 5])
print(arr2[1:4])

[1 3 3]


In [22]:
# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
n = array.size
N = 4
M = n//N
reshaped1 = array.reshape((N, M))
print("First Reshaped Array : ")
print(reshaped1)
reshaped2 = np.reshape(array, (2, 8))
print("Second Reshaped Array : ")
print(reshaped2)

First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [1]:
import numpy as np
#creating a rank 1 array
arr = np.array([1,2,3])
print(arr)

#creating a rank 2 array
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr2)

#creating array from tuple
arr3 = np.array((1,6,5))
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 6 5]


In [ ]:
import numpy as np
array = np.array([[1,2,3,4],
                  [5,7,8,9],
                  [2,7,6,5],
                  [3,5,6,7]],
                 )
# Printing a range of Array
# with the use of slicing method
arr2 = array[:2, ::2]

print("first 2 rows and alternate columns(0 and 2)" , arr2)

first 2 rows and alternate columns(0 and 2) [[1 3]
 [5 8]]


In [ ]:
import numpy as np
a = np.array(([1,2] , [3,4]))
b = np.array(([4,6] , [2,1]))

print("Adding 1 to all array elements: " , a + 1)
print("Subtracting 2 from all array elements : " , b - 2)
print("Multiplication of an array with 2 : " , a * 2)
print("Sum of array = " , a.sum())
print("Addition of two arrays : " , a + b)

Adding 1 to all array elements:  [[2 3]
 [4 5]]
Subtracting 2 from all array elements :  [[ 2  4]
 [ 0 -1]]
Multiplication of an array with 2 :  [[2 4]
 [6 8]]
Sum of array =  10
Addition of two arrays :  [[5 8]
 [5 5]]


In [ ]:
x = np.array(([1,2] , [3,4]))
print(x.dtype)

x = np.array([1.0 , 2.0])
print(x.dtype)

#forced data type
x = np.array([1,2], dtype = np.int64)
print(x.dtype)

int64
float64
int64


In [9]:
import numpy as np
arr1 = np.array([[4,7] , [3,6]], dtype = np.float64)
arr2 = np.array([[1,2] , [3,4]] , dtype = np.float64)

#sum of array
Sum = np.add(arr1 , arr2)
print(sum)

sum = np.add(arr1 , arr2)
print(sum)

sum1 = np.sum(arr1)
print(sum1)

Sqrt = np.sqrt(arr1)
print(Sqrt)

Trans_arr = arr1.T
print(Trans_arr)

<built-in function sum>
[[ 5.  9.]
 [ 6. 10.]]
20.0
[[2.         2.64575131]
 [1.73205081 2.44948974]]
[[4. 3.]
 [7. 6.]]


In [12]:
import numpy as np

arr1 = np.eye(3)
arr2 = np.linspace(0 , 10 , 5)
arr3 = np.arange(0 , 20 , 2)
arr4 = np.zeros((3,4))
arr5 = np.ones((5,7))

print(arr1)
print(arr2)
print(arr3) 
print(arr4)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0.   2.5  5.   7.5 10. ]
[ 0  2  4  6  8 10 12 14 16 18]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
