In [16]:
import numpy as np
my_list = [1,2,3,4,5]
arr = np.array(my_list)
print("Simple array ", arr)
print(arr[4])

Simple array  [1 2 3 4 5]
5


In [13]:
zeros_array = np.zeros((2,3))
ones_array = np.ones((3,3))
linspace_array = np.linspace(0,10,5)
range_array = np.arange(0,10,2)

print(zeros_array)
print(ones_array)
print(linspace_array)
print(range_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]


In [12]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
import numpy as np

random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 4)
randint_array = np.random.randint(1, 10, size=(2, 3))

print(random_array)
print(normal_array)
print(randint_array)

[[0.13262068 0.5819246  0.02992465]
 [0.28700726 0.62773317 0.26301656]]
[[ 0.95117733 -2.474124    0.1548036   0.39601704]
 [-0.26690711 -0.7475396   1.48442843  0.26029056]]
[[7 1 5]
 [6 5 7]]


In [20]:
arr1=np.array([[1,2,3,4,5],[7,8,3,6,8]])
print(arr1[1,2])

3


In [21]:
import numpy as np
arr2 = np.array([9, 1, 3, 3, 2, 5])
print(arr2[1:4])

[1 3 3]


In [22]:
# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
n = array.size
N = 4
M = n//N
reshaped1 = array.reshape((N, M))
print("First Reshaped Array : ")
print(reshaped1)
reshaped2 = np.reshape(array, (2, 8))
print("Second Reshaped Array : ")
print(reshaped2)

First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
